name: Test, Build, and Deploy

on:
  push:
    branches: ['main', 'develop', 'CSID**', 'release/**']

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.install-dependencies.outputs.cache != 'true'
        run: |
          npm install

  lint:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Unit test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          npm run deploy
