name: Test, Build, and Deploy

on:
  push:
    branches: ['main', 'develop']

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

  lint:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          npm run deploy
