name: Slack Notification

on:
  workflow_run:
    workflows:
      - Test, Build, and Deploy
    types:
      - completed
      - requested

jobs:
  on-started:
    name: Pipeline Started
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'requested' }}
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification when starts
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: redwolf-cloud-ci-cd-notifications
          SLACK_TITLE: 'DMS: Start deploy of ${{ github.event.workflow_run.head_branch }}'
          SLACK_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
          SLACK_USERNAME: SuperNeatoGithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ github.event.workflow_run.conclusion}}
          SLACK_FOOTER: ${{ github.event.workflow_run.html_url }}

  on-completed:
    name: Pipeline Completed
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'completed' }}
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification when completed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: redwolf-cloud-ci-cd-notifications
          SLACK_TITLE: 'Slack Notify: Deploy of ${{ github.event.workflow_run.head_branch }} finished with status ${{ github.event.workflow_run.conclusion}}'
          SLACK_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
          SLACK_USERNAME: SuperNeatoGithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ github.event.workflow_run.conclusion}}
          SLACK_FOOTER: ${{ github.event.workflow_run.html_url }}
