name: Update OpenAPI

on:
  workflow_run:
    workflows:
      - Test, Build, and Deploy

    types:
      - completed

jobs:
  on-completed:
    name: Send Request to Process OpenAPI
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'completed' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Send Request
        run: |
          export BASE64_APIDOC=$(cat ${{ github.workspace }}/documentation/openapi.yml | base64)
          export PAYLOAD_TEMPLATE='{"owner":"verycamilo","repo":"swagger-ci-cd-poc", "event_type":"process_openapi","client_payload":{"service":"slack-notification-test", "version": "v2", "doc": "BASE64_APIDOC"}}'
          echo $PAYLOAD_TEMPLATE | jq --arg BASE64_APIDOC "${BASE64_APIDOC}" '.client_payload.doc = $BASE64_APIDOC' > payload.json
          cat payload.json
          curl -v  \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --url https://api.github.com/repos/verycamilo/swagger-ci-cd-poc/dispatches \
          -d @payload.json

