name: Update OpenAPI

on:
  workflow_run:
    workflows:
      - Test, Build, and Deploy

    types:
      - completed

jobs:
  on-completed:
    name: Send Request to Process OpenAPI
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'completed' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files
        run: ls -ltah ${{ github.workspace }}
      - name: Encode API Doc 
        run: echo "BASE64_APIDOC=$(cat ${{ github.workspace }}/documentation/openapi.yml | base64)" >> $GITHUB_ENV        
      - name: Send Request
        # working-directory: ./documentation
        run: |          
          curl -X POST \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: Bearer ${{ secrets.SPECS_REPO_PAT }}" \
          https://api.github.com/repos/verycamilo/swagger-ci-cd-poc/dispatches \
          -d '{"event_type":"process_openapi","client_payload":{"service":"slack-notification-test", "version": "v1", "doc": "${BASE64_APIDOC}"}}'
