name: Update OpenAPI

on:
  workflow_run:
    workflows:
      - Test, Build, and Deploy
    types:
      - completed

env:  
  documentation_path: ${{ secrets.DOCUMENTATION_PATH }}
  documentation_repository: ${{ secrets.DOCUMENTATION_REPOSITORY }}

jobs:
  
  send-documentation:
    uses: verycamilo/swagger-ci-cd-poc/.github/workflows/update_api_documentation.yml@main
    with:
      documentation_path: ${{ env.documentation_path }}
      documentation_repository: ${{ env.documentation_repository }}
      stage: ${{ github.event.workflow_run.head_branch }}
    secrets:
      token: ${{ secrets.SPECS_REPO_PAT }}

      
# jobs:
  # set-stage:
  #   runs-on: ubuntu-latest
  #   name: Set Stage Name
  #   outputs:
  #     stage: ${{ steps.set-stage.outputs.stage }}
  #   steps:
  #     - id: set-stage
  #       run: |
  #         if [[ ${{ github.event.workflow_run.head_branch }} =~ ^main$ ]];
  #         then
  #             echo ::set-output name=stage::prod
  #         elif [[ ${{ github.event.workflow_run.head_branch }} =~ ^release/*$ ]];
  #             echo ::set-output name=stage::stage
  #         else
  #           echo ::set-output name=stage::${{ github.event.workflow_run.head_branch }}
  #         fi
  # on-completed:
    # needs: set-stage
    # name: Request Documenation Processing
    # uses: verycamilo/swagger-ci-cd-poc/.github/workflows/update_api_documentation.yml@main
    # if: contains(fromJSON('["develop", "stage", "preprod", "prod"]'), needs.set-stage.outputs.stage )
    # with:
    #   documentation_path: ${{ secrets.DOCUMENTATION_PATH }}
    #   documentation_repository: ${{ secrets.DOCUMENTATION_REPOSITORY }}
    #   stage: ${{ github.event.workflow_run.head_branch }}
    # secrets:
    #   token: ${{ secrets.SPECS_REPO_PAT }}
