name: Update OpenAPI

on:
  workflow_run:
    workflows:
      # - Deploy to Preprod
      # - Test, Build, and Deploy to Production
      - Test, Build, and Deploy
    types:
      - completed

jobs:
  
  send-documentation:
    
    #uses: BuddyTV/redwolf-github-workflows/.github/workflows/redwolf-cloud-update-documentation.yml@main
    uses: verycamilo/swagger-ci-cd-poc/.github/workflows/update_api_documentation.yml@main
    with:
      documentation_path: documentation/openapi.yml
    secrets:
      #token: ${{ secrets.PAT }}
      token: ${{ secrets.SPECS_REPO_PAT }}

