name: Update OpenAPI

on:
  workflow_run:
    workflows:
      - Test, Build, and Deploy

    types:
      - completed

jobs:
  on-completed:
    name: Send Request to Process OpenAPI
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'completed' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Send Request
        run: |
          export BASE64_APIDOC=$(cat ${{ github.workspace }}/documentation/openapi.yml | base64)
          export TITLE=$(cat documentation/openapi.yml| yq .info.title)
          export VERSION=$(cat documentation/openapi.yml| yq .info.version)
          export PAYLOAD_TEMPLATE='{ "event_type":"process_openapi","client_payload":{"service":"slack-notification-test", "version": "VERSION", "doc": "BASE64_APIDOC", "title":"TITLE"}}'
          echo $PAYLOAD_TEMPLATE | jq --arg BASE64_APIDOC "${BASE64_APIDOC}" --arg TITLE "${TITLE}" --arg VERSION "${VERSION}" '.client_payload.doc = $BASE64_APIDOC | .client_payload.title = $TITLE | .client_payload.version=$VERSION' > payload.json
          cat payload.json
          curl -v  \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.SPECS_REPO_PAT }}" \
          --url https://api.github.com/repos/verycamilo/swagger-ci-cd-poc/dispatches \
          -d @payload.json
